// <auto-generated />
using System;
using CotecnaB.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CotecnaB.Persistance.Migrations
{
    [DbContext(typeof(CotecnaEFContext))]
    [Migration("20200126214530_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CotecnaB.Core.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime?>("Modified");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("CotecnaB.Core.Entities.InspectionInspector", b =>
                {
                    b.Property<Guid>("InspectionId");

                    b.Property<Guid>("InspectorId");

                    b.Property<DateTime>("InspectionDate");

                    b.HasKey("InspectionId", "InspectorId", "InspectionDate");

                    b.HasIndex("InspectorId");

                    b.ToTable("InspectionInspector");
                });

            modelBuilder.Entity("CotecnaB.Core.Entities.Inspection", b =>
                {
                    b.HasBaseType("CotecnaB.Core.Entities.BaseEntity");

                    b.Property<string>("Address");

                    b.Property<string>("Customer");

                    b.Property<string>("Observations");

                    b.Property<int>("Status");

                    b.HasDiscriminator().HasValue("Inspection");
                });

            modelBuilder.Entity("CotecnaB.Core.Entities.Inspector", b =>
                {
                    b.HasBaseType("CotecnaB.Core.Entities.BaseEntity");

                    b.Property<string>("Name");

                    b.HasDiscriminator().HasValue("Inspector");
                });

            modelBuilder.Entity("CotecnaB.Core.Entities.InspectionInspector", b =>
                {
                    b.HasOne("CotecnaB.Core.Entities.Inspection", "Inspection")
                        .WithMany("InspectionInspector")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CotecnaB.Core.Entities.Inspector", "Inspector")
                        .WithMany("InspectionInspector")
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
